target-version = "py312"
line-length = 88

[lint]
extend-select = [
    "E",    # pycodestyle (PEP 8 errors)
    "F",    # pyflakes
    "N",    # pep8-naming
    "PD",   # pandas-vet
    "PTH",  # pathlib rules
    "E501", #Line length
    "I"     #isort
]
[lint.per-file-ignores]
"create_data/*" = ["E501", "N803"]
